def test_do():
    event = {'resource': '/command_poll', 'path': '/command_poll', 'httpMethod': 'POST',
             'headers': {'Accept': 'application/json,*/*', 'Accept-Encoding': 'gzip,deflate',
                         'CloudFront-Forwarded-Proto': 'https', 'CloudFront-Is-Desktop-Viewer': 'true',
                         'CloudFront-Is-Mobile-Viewer': 'false', 'CloudFront-Is-SmartTV-Viewer': 'false',
                         'CloudFront-Is-Tablet-Viewer': 'false', 'CloudFront-Viewer-Country': 'US',
                         'Content-Type': 'application/x-www-form-urlencoded',
                         'Host': 'hby6zd3tfb.execute-api.ap-northeast-2.amazonaws.com',
                         'User-Agent': 'Slackbot 1.0 (+https://api.slack.com/robots)',
                         'Via': '1.1 a4cae74c829bc214e4183c38164a2c0a.cloudfront.net (CloudFront)',
                         'X-Amz-Cf-Id': 'hB0dqQxYM78tBEyQfpp8MzdSqhSK340KqwYFhDBMKgZHUEyH3x_Dig==',
                         'X-Amzn-Trace-Id': 'Root=1-5e7e931b-62687c7abbacd39e514e19b4',
                         'X-Forwarded-For': '3.81.121.107, 130.176.98.96', 'X-Forwarded-Port': '443',
                         'X-Forwarded-Proto': 'https', 'X-Slack-Request-Timestamp': '1585353498',
                         'X-Slack-Signature': 'v0=c6647dce9adf85ea9043847d4f84a21f46a9345a7abaeebe1f0cc700d75316b6'},
             'multiValueHeaders': {'Accept': ['application/json,*/*'], 'Accept-Encoding': ['gzip,deflate'],
                                   'CloudFront-Forwarded-Proto': ['https'], 'CloudFront-Is-Desktop-Viewer': ['true'],
                                   'CloudFront-Is-Mobile-Viewer': ['false'], 'CloudFront-Is-SmartTV-Viewer': ['false'],
                                   'CloudFront-Is-Tablet-Viewer': ['false'], 'CloudFront-Viewer-Country': ['US'],
                                   'Content-Type': ['application/x-www-form-urlencoded'],
                                   'Host': ['hby6zd3tfb.execute-api.ap-northeast-2.amazonaws.com'],
                                   'User-Agent': ['Slackbot 1.0 (+https://api.slack.com/robots)'],
                                   'Via': ['1.1 a4cae74c829bc214e4183c38164a2c0a.cloudfront.net (CloudFront)'],
                                   'X-Amz-Cf-Id': ['hB0dqQxYM78tBEyQfpp8MzdSqhSK340KqwYFhDBMKgZHUEyH3x_Dig=='],
                                   'X-Amzn-Trace-Id': ['Root=1-5e7e931b-62687c7abbacd39e514e19b4'],
                                   'X-Forwarded-For': ['3.81.121.107, 130.176.98.96'], 'X-Forwarded-Port': ['443'],
                                   'X-Forwarded-Proto': ['https'], 'X-Slack-Request-Timestamp': ['1585353498'],
                                   'X-Slack-Signature': [
                                       'v0=c6647dce9adf85ea9043847d4f84a21f46a9345a7abaeebe1f0cc700d75316b6']},
             'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'pathParameters': None,
             'stageVariables': None,
             'requestContext': {'resourceId': 'ohs34g', 'resourcePath': '/command_poll', 'httpMethod': 'POST',
                                'extendedRequestId': 'KEvsPHA9IE0FpeQ=', 'requestTime': '27/Mar/2020:23:58:19 +0000',
                                'path': '/default/command_poll', 'accountId': '237943334087', 'protocol': 'HTTP/1.1',
                                'stage': 'default', 'domainPrefix': 'hby6zd3tfb', 'requestTimeEpoch': 1585353499017,
                                'requestId': '4ea9b215-e60f-412a-93a8-dbc9babf6a52',
                                'identity': {'cognitoIdentityPoolId': None, 'accountId': None, 'cognitoIdentityId': None,
                                             'caller': None, 'sourceIp': '3.81.121.107', 'principalOrgId': None,
                                             'accessKey': None, 'cognitoAuthenticationType': None,
                                             'cognitoAuthenticationProvider': None, 'userArn': None,
                                             'userAgent': 'Slackbot 1.0 (+https://api.slack.com/robots)', 'user': None},
                                'domainName': 'hby6zd3tfb.execute-api.ap-northeast-2.amazonaws.com', 'apiId': 'hby6zd3tfb'},
             'body': 'token=FcLrpGmG3VeCuyd7bUMQszKz&team_id=T48RY2MFH&team_domain=restrictedzone&channel_id=CGK4QNXNC&channel_name=bot_test&user_id=U78RDCCJE&user_name=lastone9182&command=%2Fdo&text=test&response_url=https%3A%2F%2Fhooks.slack.com%2Fcommands%2FT48RY2MFH%2F1034664201526%2FBFUzmYjdPVTsEWfYjl1sG6Pj&trigger_id=1020016351522.144882089527.35ebbd10f7ade86dda86a8f71a81012b',
             'isBase64Encoded': False}
